const $ = id => document.getElementById(id);
let dataState = null, inboxFilter = "urgent", editMode = false;
const defaultOrbit=[{id:"gmail",icon:"✉️",screen:"inbox",x:18,y:10,count:"orbitMail"},{id:"calendar",icon:"📅",screen:"calendar",x:70,y:10,count:"orbitCal"},{id:"whatsapp",icon:"💬",screen:"social",x:84,y:43},{id:"files",icon:"📁",screen:"files",x:69,y:75},{id:"media",icon:"🎵",screen:"media",x:22,y:75},{id:"system",icon:"⚙️",screen:"system",x:4,y:43}];
let orbit=JSON.parse(localStorage.getItem("aura_orbit_v33")||"null")||defaultOrbit;
function esc(v){return String(v??"").replace(/[&<>"']/g,s=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[s]))}
function fmt(v){if(!v)return"";const d=new Date(v);return Number.isNaN(d.getTime())?esc(v):d.toLocaleString("he-IL",{hour:"2-digit",minute:"2-digit",day:"2-digit",month:"2-digit"})}
async function getJson(url){const res=await fetch(url,{credentials:"include",cache:"no-store"});const data=await res.json().catch(()=>({error:"Bad response"}));return{ok:res.ok,data}}
function renderOrbit(){$("orbitApps").innerHTML=orbit.map(a=>`<button class="orb-icon" data-id="${a.id}" data-screen="${a.screen}" style="left:${a.x}%;top:${a.y}%"><span>${a.icon}</span><small id="${a.count||""}">${a.count?"0":""}</small><i class="x">×</i></button>`).join("");wireOrbit()}
function wireOrbit(){let pressTimer=null,drag=null;document.querySelectorAll(".orb-icon").forEach(btn=>{btn.onclick=e=>{if(editMode){e.preventDefault();return}openScreen(btn.dataset.screen)};btn.onpointerdown=e=>{pressTimer=setTimeout(()=>setEditMode(true),650);if(editMode){drag={el:btn,id:btn.dataset.id};btn.setPointerCapture(e.pointerId);btn.classList.add("dragging")}};btn.onpointermove=e=>{if(!drag||drag.el!==btn)return;const r=$("orbitZone").getBoundingClientRect(),x=Math.max(0,Math.min(88,((e.clientX-r.left)/r.width)*100-8)),y=Math.max(0,Math.min(88,((e.clientY-r.top)/r.height)*100-8));btn.style.left=x+"%";btn.style.top=y+"%";const item=orbit.find(o=>o.id===drag.id);if(item){item.x=Math.round(x);item.y=Math.round(y)}};btn.onpointerup=()=>{clearTimeout(pressTimer);if(drag){localStorage.setItem("aura_orbit_v33",JSON.stringify(orbit));btn.classList.remove("dragging");drag=null}};btn.querySelector(".x").onclick=e=>{e.stopPropagation();orbit=orbit.filter(o=>o.id!==btn.dataset.id);localStorage.setItem("aura_orbit_v33",JSON.stringify(orbit));renderOrbit()}})}
function setEditMode(on){editMode=on;document.body.classList.toggle("edit-mode",on);$("mainText").textContent=on?"Edit Mode: drag icons, remove with ×, tap ✦ to finish.":"Edit mode closed."}
function openScreen(id){setEditMode(false);document.querySelectorAll(".screen").forEach(s=>s.classList.toggle("active",s.id===id));document.querySelectorAll(".dock button").forEach(b=>b.classList.toggle("active",b.dataset.screen===id));scrollTo({top:0,behavior:"smooth"})}
window.openScreen=openScreen;
function emailBucket(e){const txt=`${e.subject} ${e.snippet} ${e.from}`.toLowerCase();if(e.type==="Billing")return"billing";if(e.priority==="High")return"urgent";if(txt.includes("reply")||txt.includes("approval")||txt.includes("approve"))return"reply";return"info"}
function renderInbox(){const emails=dataState?.emails||[],groups={urgent:[],reply:[],billing:[],info:[]};emails.forEach(e=>groups[emailBucket(e)].push(e));$("inboxSummary").innerHTML=Object.entries(groups).map(([k,v])=>`<div><b>${v.length}</b><span>${k}</span></div>`).join("");const list=groups[inboxFilter]||[];$("mailGroups").innerHTML=list.length?list.map(e=>`<div class="mail-card ${inboxFilter}"><b>${esc(e.subject||"(No subject)")}</b><span>${esc(e.from||"")}</span><span>${esc(e.snippet||"")}</span><span class="tag ${inboxFilter==="billing"?"gold":inboxFilter==="urgent"?"red":"blue"}">${esc(e.priority||"Normal")}</span><button onclick="openEmail(${emails.indexOf(e)})">Open Email</button></div>`).join(""):`<div class="muted">Nothing in this group.</div>`}
function openEmail(idx){const e=(dataState?.emails||[])[idx];if(!e)return;$("modalTitle").textContent=e.subject||"Email";$("modalBody").innerHTML=`<p><b>From:</b> ${esc(e.from||"")}</p><p>${esc(e.date||"")}</p><p>${esc(e.snippet||"")}</p>`;$("detailModal").classList.add("active")} window.openEmail=openEmail;
function renderTimeline(events){$("timeline").innerHTML=events.length?events.map((e,i)=>`<div class="timeline-item"><b>${fmt(e.start)}</b><span>${esc(e.summary||"(No title)")}</span>${e.location?`<span>${esc(e.location)}</span>`:""}<button onclick="openEvent(${i})">Open Event</button></div>`).join(""):`<div class="muted">No upcoming events.</div>`}
function openEvent(i){const e=(dataState?.events||[])[i];if(!e)return;$("modalTitle").textContent=e.summary||"Calendar Event";$("modalBody").innerHTML=`<p><b>Time:</b> ${fmt(e.start)}</p><p><b>Location:</b> ${esc(e.location||"")}</p><p>${esc(e.description||"")}</p>`;$("detailModal").classList.add("active")} window.openEvent=openEvent;
function addChat(role,text,actions=[]){$("chatList").insertAdjacentHTML("beforeend",`<div class="chat-message ${role}"><b>${role==="user"?"Moshe":"Sofia"}</b><p>${esc(text)}</p>${actions.length?`<div class="chat-actions">${actions.map(a=>`<button onclick="${a.run}">${a.label}</button>`).join("")}</div>`:""}</div>`);$("chatList").scrollTop=$("chatList").scrollHeight}
function feedCard(icon,title,sub,target,btn="Open"){return`<div class="feed-card"><b>${icon} ${esc(title)}</b><span>${esc(sub)}</span>${target?`<button onclick="openScreen('${target}')">${btn}</button>`:""}</div>`}
function renderHome(d){const sof=d.sofia||{},g=sof.gmail||{},c=sof.calendar||{},actions=sof.recommendedActions||[],emails=d.emails||[],events=d.events||[];$("notifyCount").textContent=String((g.highPriority||0)+actions.length);if($("orbitMail"))$("orbitMail").textContent=String(g.highPriority||0);if($("orbitCal"))$("orbitCal").textContent=String(c.total||0);$("sofiaState").textContent="live";$("mainText").textContent=sof.message||"Sofia has prepared your briefing.";$("actionCenter").innerHTML=[feedCard("🔴",`${g.highPriority||0} emails need attention`,`${g.billing||0} billing emails detected`,"inbox","Open Inbox"),feedCard("🟠",events[0]?.summary||"No next meeting",events[0]?fmt(events[0].start):"Calendar clear","calendar","Open Calendar"),...actions.slice(0,3).map(a=>feedCard("✅",a,"Recommended by Sofia","inbox","Open"))].join("");$("alertList").innerHTML=$("actionCenter").innerHTML;renderInbox();renderTimeline(events)}
async function loadBriefing(){$("mainText").textContent="Sofia is reading Gmail and Calendar…";const {ok,data}=await getJson("/.netlify/functions/google-briefing");if(!ok){$("mainText").textContent=data.error||"Briefing failed";return}dataState=data;renderHome(data);addChat("sofia",data.sofia?.message||"הבריפינג מוכן.",[{label:"Open Inbox",run:"openScreen('inbox')"},{label:"Open Calendar",run:"openScreen('calendar')"}])}
async function getGeo(){return new Promise(resolve=>{if(!navigator.geolocation)return resolve({});navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lon:p.coords.longitude}),()=>resolve({}),{enableHighAccuracy:false,timeout:2500,maximumAge:600000})})}
async function askSofiaServer(message){const geo=await getGeo();const res=await fetch("/.netlify/functions/sofia-chat",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,...geo})});if(!res.ok)throw new Error("chat function failed");return await res.json()}
function detectActions(answer){const a=String(answer||"").toLowerCase(),out=[];if(a.includes("מייל")||a.includes("email")||a.includes("inbox"))out.push({label:"Open Inbox",run:"openScreen('inbox')"});if(a.includes("פגישה")||a.includes("calendar")||a.includes("יומן"))out.push({label:"Open Calendar",run:"openScreen('calendar')"});if(a.includes("weather")||a.includes("מזג"))out.push({label:"System",run:"openScreen('system')"});return out}
async function ask(){const q=$("askInput").value.trim();if(!q)return;$("askInput").value="";addChat("user",q);$("mainText").textContent="Sofia is thinking…";try{const data=await askSofiaServer(q);const ans=data.reply||"אני כאן משה.";$("mainText").textContent=ans;addChat("sofia",ans,detectActions(ans));speak(ans)}catch(e){const ans="יש בעיה זמנית בחיבור לשיחה של Sofia. בדוק שהקובץ netlify/functions/sofia-chat.js עלה ל-GitHub ושבוצע Deploy תקין.";$("mainText").textContent=ans;addChat("sofia",ans);speak(ans)}}
function speak(text){if("speechSynthesis"in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text||$("mainText").textContent);u.lang="he-IL";u.rate=.95;u.pitch=1.05;speechSynthesis.speak(u)}$("voiceBar").classList.add("active");setTimeout(()=>$("voiceBar").classList.remove("active"),4000)}
function startVoiceInput(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){speak("המכשיר הזה לא תומך בהכתבה קולית בדפדפן. אפשר להקליד לי.");return}const rec=new R();rec.lang="he-IL";rec.interimResults=false;rec.maxAlternatives=1;$("voiceBar").classList.add("active");rec.onresult=e=>{$("askInput").value=e.results[0][0].transcript;ask()};rec.onend=()=>$("voiceBar").classList.remove("active");rec.start()}
async function status(){const {ok,data}=await getJson("/.netlify/functions/status");$("systemList").innerHTML=[["Gmail",data.hasToken&&data.hasClientId],["Calendar",data.hasToken&&data.hasClientId],["Sofia Chat",ok],["OpenAI",data.hasOpenAI],["WhatsApp",false],["Functions",ok]].map(([n,on])=>`<div class="system-row"><b>${n}</b><span class="dot ${on?"ok":""}"></span></div>`).join("")}
document.querySelectorAll("[data-screen]").forEach(b=>b.addEventListener("click",()=>openScreen(b.dataset.screen)));
document.querySelectorAll(".segment").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".segment").forEach(x=>x.classList.remove("active"));b.classList.add("active");inboxFilter=b.dataset.filter;renderInbox()}));
document.querySelectorAll(".quick-actions button").forEach(b=>b.addEventListener("click",()=>{$("askInput").value=b.dataset.q;ask()}));
$("briefBtn").onclick=loadBriefing;$("briefBtn2").onclick=loadBriefing;$("connectBtn").onclick=()=>location.href="/.netlify/functions/google-auth";$("talkBtn").onclick=startVoiceInput;$("voiceBtn").onclick=startVoiceInput;$("readBtn").onclick=()=>speak();$("askSend").onclick=ask;$("askInput").onkeydown=e=>{if(e.key==="Enter")ask()};$("editToggle").onclick=()=>setEditMode(!editMode);$("resetLayoutBtn").onclick=()=>{orbit=defaultOrbit;localStorage.setItem("aura_orbit_v33",JSON.stringify(orbit));renderOrbit()};$("refreshBtn").onclick=status;$("notifyBtn").onclick=()=>$("notificationCenter").classList.add("active");$("closeNotify").onclick=()=>$("notificationCenter").classList.remove("active");$("closeModal").onclick=()=>$("detailModal").classList.remove("active");$("clearActionsBtn").onclick=()=>$("actionCenter").innerHTML='<div class="muted">Cleared.</div>';$("openWhatsapp")?.addEventListener("click",()=>{location.href="https://wa.me/"});renderOrbit();status();
